CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_CPI=2400
CONFIG_PMW3610_ALT_CPI_DIVIDOR=4
CONFIG_PMW3610_ALT_ORIENTATION_270=y
CONFIG_PMW3610_ALT_SNIPE_CPI=800
CONFIG_PMW3610_ALT_SNIPE_CPI_DIVIDOR=4
CONFIG_PMW3610_ALT_SCROLL_TICK=32
CONFIG_PMW3610_ALT_INVERT_X=y

CONFIG_PMW3610_ALT_POLLING_RATE_125_SW=y
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
